spring:
  application:
    name: adr
  datasource:
    url: jdbc:postgresql://localhost:5432/adr
    driverClassName: org.postgresql.Driver
    username: adr_user
    password: S3cret
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
    ddl-auto: update
    show-sql: true
    format-sql: true
  h2:
    console:
      enabled: true
  output:
    ansi:
      enabled: always
