
spring:
  application:
    name: adr
  datasource:
    url: jdbc:postgresql://postgres:5432/adr
    driverClassName: org.postgresql.Driver
    username: adr_user
    password: S3cret
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
    ddl-auto: update
    show-sql: true
    format-sql: true
  h2:
    console:
      enabled: true
  output:
    ansi:
      enabled: always
server:
  port: 8085

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs.path: /api-docs

data:
  ikm:
    enabled: false
  path:
    parent: /data
    child: solor-us-tinkar.sa