version: '3'
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ../data/postgress:/var/lib/postgresql/data
      - ../database/adr.sql:/docker-entrypoint-initdb.d/adr.sql
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=adr_user
      - POSTGRES_DB=adr
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5