version: '3'
networks:
  opencdx-network:
    external: true
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ../data/postgress:/var/lib/postgresql/data
      - ../database/adr.sql:/docker-entrypoint-initdb.d/adr.sql
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=adr_user
      - POSTGRES_DB=adr
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  adr:
    deploy:
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 5
        window: 60s
    image: adr:latest
    ports:
      - 8085:8085
    healthcheck:
      test: "curl -k --fail --silent https://localhost:8080/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 5s
      retries: 10