package cdx.opencdx.adr.model;

public enum DurationType {
    DURATION_TYPE_NOT_SPECIFIED,
    DURATION_TYPE_MILLISECONDS,
    DURATION_TYPE_SECONDS,
    DURATION_TYPE_MINUTES,
    DURATION_TYPE_HOURS,
    DURATION_TYPE_DAYS,
    DURATION_TYPE_WEEKS,
    DURATION_TYPE_MONTHS,
    DURATION_TYPE_YEARS
}